### ISSUE TITLE
魅族手机无法识别被拒绝的权限

### ISSUE THREAD

**Issue by Khaos116** [crazyqiang/Aopermission#1]
魅蓝5S在安装APP后去权限管理关闭权限后，再打开APP进行权限请求，得到的全是通过，但实际全部都是被拒绝了的

**Comment by android-zk** [comment]
运行demo安装App，点击申请权限全是通过，实际都是被询问状态，代码一点都没有动，是我下载了假的demo吗？

**Comment by crazyqiang** [comment]
系统版本是多少 项目里调用的是系统标准的API去申请权限的，  6.0以上的话就需要做兼容了 国产手机没法，只能去做兼容 ；如果是6.0以下  系统默认就是通过
