### ISSUE TITLE
多进程会有问题

### ISSUE THREAD

**Issue by shicaiD** [crazyqiang/Aopermission#3]
这种方式对于单进程还不错，在多线程时就会出现问题。
在非主进程中调用@NeedPermission()，最终PermissionRequestActivity会运行在主进程中，从而无法回调权限申请结果。

**Comment by crazyqiang** [comment]
多进程还是多线程？多进程没试过。如果是多线程，为什么要在子线程中去申请权限呢？

**Comment by shicaiD** [comment]
> 多进程还是多线程？多进程没试过。如果是多线程，为什么要在子线程中去申请权限呢？

是多进程，你可以测试一下

**Comment by crazyqiang** [comment]
你的使用场景是什么  为什么会去其他的进程中申请权限呢？

**Comment by shicaiD** [comment]
> 你的使用场景是什么 为什么会去其他的进程中申请权限呢？

在另外的进程有使用到相机的时候，以防万一，还是要检查权限呀

**Comment by crazyqiang** [comment]
目前不支持多进程  这种场景毕竟很有限  后续考虑支持吧  多进程的时候你先手动去申请一下吧
