### ISSUE TITLE
Only fullscreen opaque activities can request orientation

### ISSUE THREAD

**Issue by 448973841** [crazyqiang/Aopermission#4]
主要是SdkVersion 27 以上有异常，没有兼容8.0

**Comment by amosxb** [comment]
> 主要是SdkVersion 27 以上有异常，没有兼容8.0

这个问题是系统8.0所特有的问题，意思是Android8.0为了支持全面屏，增加了一个限制：如果是透明的Activity，则不能固定它的方向，因为它的方向其实是依赖其父Activity的（因为透明）。这个bug只有在8.0中有，8.1中已经修复。解决的办法可以不通过lib引用方式，直接把lib包导进来，把           android:screenOrientation="portrait"给删了。

**Comment by crazyqiang** [comment]
新版本(1.2.0)已解决该问题
